# Multi-Resistance Antibiotic Susceptibility

## Fase 0 – Preparación y perfilado

In [1]:
# %% [markdown]
# ## Fase 0 – Preparación y perfilado del dataset

# %%
import pandas as pd
import numpy as np

# Opciones de visualización
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 140)

In [3]:
# %%
DATA_PATH = "Bacteria_dataset_Multiresictance.csv"

df = pd.read_csv(DATA_PATH)

df.shape, df.columns.tolist()

((10710, 27),
 ['ID',
  'Name',
  'Email',
  'Address',
  'age/gender',
  'Souches',
  'Diabetes',
  'Hypertension',
  'Hospital_before',
  'Infection_Freq',
  'AMX/AMP',
  'AMC',
  'CZ',
  'FOX',
  'CTX/CRO',
  'IPM',
  'GEN',
  'AN',
  'Acide nalidixique',
  'ofx',
  'CIP',
  'C',
  'Co-trimoxazole',
  'Furanes',
  'colistine',
  'Collection_Date',
  'Notes'])

In [4]:
df

,ID,Name,Email,Address,age/gender,Souches,Diabetes,Hypertension,Hospital_before,Infection_Freq,AMX/AMP,AMC,CZ,FOX,CTX/CRO,IPM,GEN,AN,Acide nalidixique,ofx,CIP,C,Co-trimoxazole,Furanes,colistine,Collection_Date,Notes
0,S290,Elizabeth Lawrence,elizabeth.lawrence@example.com,"6350 Robinson Loaf Apt. 447, Paulfurt, RI 30252",37/F,S290 Escherichia coli,No,No,No,0.0,R,R,R,R,R,R,S,S,S,S,S,R,S,S,S,5 Fev 2025,Patient had fever??
1,S291,Tina Sanders,tina.sanders@example.com,"78594 Galloway Port Suite 762, South Tanyatown...",29/F,S291 Morganella morganii,True,No,No,3.0,S,R,S,R,S,R,S,S,S,S,S,S,S,S,S,08/05/2021,تم العلاج
2,S292,Erin Cooke,erin.cooke@example.com,"76661 Isaiah Manors, North Benjamin, HI 85195",77/F,S292 Proteus mirabilis,True,No,No,3.0,S,R,S,R,S,S,S,S,S,S,R,R,S,S,S,01/05/2022,NADA
3,S293,Mrs. Sharon Watson,mrs..sharon.watson@example.com,"1670 Thompson Way Apt. 520, Andrewbury, IL 11534",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-05,PACIENTO ENFERMO
4,S294,Erika Stewart,erika.stewart@example.com,"76838 Patrick Green Suite 538, Torresmouth, ME...",13/F,S294 Escherichia coli,No,Yes,No,1.0,S,S,R,R,R,R,R,R,S,S,S,S,S,S,S,error,NADA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10705,S10995,Mrs. Chelsea Brown MD,mrs..chelsea.brown.md@example.com,"23574 Palmer Lodge, South Aliciaton, GU 00728",17/M,S7382 Enterobacteria spp.,No,No,No,3.0,S,R,R,S,S,R,S,S,S,S,S,S,S,S,S,2024-12-31,see file
10706,S10996,Mary Kelley,mary.kelley@example.com,"8194 Gonzalez Hill, Loveview, SD 31189",20/F,S1479 Proeus mirabilis,True,No,Yes,3.0,S,R,S,S,S,S,S,S,S,S,S,S,S,S,S,5 Fev 2025,Patient had fever??
10707,S10997,Alexandra Smith,alexandra.smith@example.com,"213 Yates Station, Port Meganstad, PW 17799",33/M,S2983 Escherichia coli,No,No,No,0.0,R,R,S,R,R,R,S,S,S,R,S,R,S,S,S,08/05/2021,Patient had fever??
10708,S10998,April Cox,april.cox@example.com,"985 Julia Freeway Apt. 753, Dianamouth, SD 07610",86/F,S10079 Escherichia coli,No,No,No,2.0,Intermediate,s,r,i,r,Intermediate,r,s,i,r,r,s,Intermediate,r,s,05/03/2022,see file
10709,S10999,Richard Jarvis,richard.jarvis@example.com,"2903 James Motorway Suite 202, Whitakerside, C...",?,NaN,missing,?,NaN,NaN,NaN,missing,?,?,NaN,NaN,missing,NaN,NaN,missing,NaN,?,?,NaN,?,?,NaN

In [5]:
# %%
# Definir grupos lógicos de columnas (según el reporte y la metadata)

ID_COL = "ID"

PII_COLS = ["Name", "Email", "Address"]  # se eliminarán más adelante

DEMOGRAPHIC_COLS = ["age/gender", "Souches"]

RISK_FACTOR_COLS = ["Diabetes", "Hypertension", "Hospital_before", "Infection_Freq"]

ANTIBIOTIC_COLS = [
    "AMX/AMP",
    "AMC",
    "CZ",
    "FOX",
    "CTX/CRO",
    "IPM",
    "GEN",
    "AN",
    "Acide nalidixique",
    "ofx",
    "CIP",
    "C",
    "Co-trimoxazole",
    "Furanes",
    "colistine",
]

META_COLS = ["Collection_Date", "Notes"]

ALL_EXPECTED_COLS = (
    [ID_COL]
    + PII_COLS
    + DEMOGRAPHIC_COLS
    + RISK_FACTOR_COLS
    + ANTIBIOTIC_COLS
    + META_COLS
)

# Comprobemos que todo está en el DataFrame
missing_cols = [c for c in ALL_EXPECTED_COLS if c not in df.columns]
extra_cols = [c for c in df.columns if c not in ALL_EXPECTED_COLS]

missing_cols, extra_cols

([], [])

In [6]:
# %%
# Info básica de tipos, memoria y primeras filas
print("Shape:", df.shape)
print("\nTipos de datos:")
print(df.dtypes)

mem_mb = df.memory_usage(deep=True).sum() / 1024**2
print(f"\nUso aproximado de memoria: {mem_mb:.2f} MB")

Shape: (10710, 27)

Tipos de datos:
ID                   object
Name                 object
Email                object
Address              object
age/gender           object
Souches              object
Diabetes             object
Hypertension         object
Hospital_before      object
Infection_Freq       object
AMX/AMP              object
AMC                  object
CZ                   object
FOX                  object
CTX/CRO              object
IPM                  object
GEN                  object
AN                   object
Acide nalidixique    object
ofx                  object
CIP                  object
C                    object
Co-trimoxazole       object
Furanes              object
colistine            object
Collection_Date      object
Notes                object
dtype: object

Uso aproximado de memoria: 14.94 MB

In [7]:
# %%
def build_column_profile(data: pd.DataFrame, sample_size: int = 5) -> pd.DataFrame:
    """
    Construye un perfil inicial por columna:
    - dtype
    - n_distinct
    - n_missing
    - pct_missing
    - ejemplos de valores no nulos
    """
    records = []
    n_rows = len(data)

    for col in data.columns:
        series = data[col]
        n_missing = series.isna().sum()
        pct_missing = (n_missing / n_rows) * 100 if n_rows > 0 else np.nan
        n_distinct = series.nunique(dropna=True)

        sample_values = series.dropna().astype(str).unique()[:sample_size].tolist()

        records.append(
            {
                "columna": col,
                "dtype": str(series.dtype),
                "n_distinct": int(n_distinct),
                "n_missing": int(n_missing),
                "pct_missing": round(pct_missing, 2),
                "ejemplos": sample_values,
            }
        )

    profile_df = pd.DataFrame(records).sort_values("columna")
    return profile_df


column_profile = build_column_profile(df)
column_profile

              columna   dtype  n_distinct  n_missing  pct_missing                                           ejemplos
11                AMC  object           8        632         5.90                         [R, S, s, r, Intermediate]
10            AMX/AMP  object           8        658         6.14                                    [R, S, s, i, ?]
17                 AN  object           8        628         5.86                              [S, R, i, missing, s]
18  Acide nalidixique  object           8        622         5.81                         [S, R, Intermediate, s, r]
3             Address  object       10710          0         0.00  [6350 Robinson Loaf Apt. 447, Paulfurt, RI 302...
21                  C  object           8        629         5.87                         [R, S, Intermediate, i, ?]
20                CIP  object           8        633         5.91                         [S, R, s, Intermediate, i]
14            CTX/CRO  object           8        624         5.83                                    [R, S, r, i, ?]
12                 CZ  object           8        628         5.86                         [R, S, r, Intermediate, ?]
22     Co-trimoxazole  object           8        640         5.98                         [S, R, Intermediate, s, r]
25    Collection_Date  object          13        669         6.25  [5 Fev 2025, 08/05/2021, 01/05/2022, 2020-01-0...
6            Diabetes  object           4        635         5.93                             [No, True, ?, missing]
2               Email  object       10005          0         0.00  [elizabeth.lawrence@example.com, tina.sanders@...
13                FOX  object           8        625         5.84                                    [R, S, s, ?, i]
23            Furanes  object           8        637         5.95                                    [S, R, i, s, r]
16                GEN  object           8        643         6.00                                    [S, R, i, s, r]
8     Hospital_before  object           4        637         5.95                              [No, Yes, ?, missing]
7        Hypertension  object           4        630         5.88                              [No, Yes, ?, missing]
0                  ID  object       10710          0         0.00                     [S290, S291, S292, S293, S294]
15                IPM  object           8        633         5.91                         [R, S, i, Intermediate, s]
9      Infection_Freq  object           8        639         5.97                      [0.0, 3.0, 1.0, 2.0, unknown]
1                Name  object       10005          0         0.00  [Elizabeth Lawrence, Tina Sanders, Erin Cooke,...
26              Notes  object           9        112         1.05  [Patient had fever??, تم العلاج, NADA, PACIENT...
5             Souches  object        9298        640         5.98  [S290 Escherichia coli, S291 Morganella morgan...
4          age/gender  object         184        621         5.80                     [37/F, 29/F, 77/F, 13/F, 57/M]
24          colistine  object           8        636         5.94                              [S, R, r, missing, i]
19                ofx  object           8        618         5.77                         [S, R, r, Intermediate, s]

In [ ]:
# Si quieres ver solo algunas columnas (por ejemplo, factores de riesgo + antibióticos):
# %%
column_profile[column_profile["columna"].isin(RISK_FACTOR_COLS + ANTIBIOTIC_COLS)]

              columna   dtype  n_distinct  n_missing  pct_missing                       ejemplos
11                AMC  object           8        632         5.90     [R, S, s, r, Intermediate]
10            AMX/AMP  object           8        658         6.14                [R, S, s, i, ?]
17                 AN  object           8        628         5.86          [S, R, i, missing, s]
18  Acide nalidixique  object           8        622         5.81     [S, R, Intermediate, s, r]
21                  C  object           8        629         5.87     [R, S, Intermediate, i, ?]
20                CIP  object           8        633         5.91     [S, R, s, Intermediate, i]
14            CTX/CRO  object           8        624         5.83                [R, S, r, i, ?]
12                 CZ  object           8        628         5.86     [R, S, r, Intermediate, ?]
22     Co-trimoxazole  object           8        640         5.98     [S, R, Intermediate, s, r]
6            Diabetes  object           4        635         5.93         [No, True, ?, missing]
13                FOX  object           8        625         5.84                [R, S, s, ?, i]
23            Furanes  object           8        637         5.95                [S, R, i, s, r]
16                GEN  object           8        643         6.00                [S, R, i, s, r]
8     Hospital_before  object           4        637         5.95          [No, Yes, ?, missing]
7        Hypertension  object           4        630         5.88          [No, Yes, ?, missing]
15                IPM  object           8        633         5.91     [R, S, i, Intermediate, s]
9      Infection_Freq  object           8        639         5.97  [0.0, 3.0, 1.0, 2.0, unknown]
24          colistine  object           8        636         5.94          [S, R, r, missing, i]
19                ofx  object           8        618         5.77     [S, R, r, Intermediate, s]

In [9]:
# Porcentaje de valores faltantes por columna
# %%
missing_summary = (
    df.isna()
    .mean()
    .mul(100)
    .round(2)
    .rename("pct_missing")
    .to_frame()
    .sort_values("pct_missing", ascending=False)
)

missing_summary

                   pct_missing
Collection_Date           6.25
AMX/AMP                   6.14
GEN                       6.00
Souches                   5.98
Co-trimoxazole            5.98
Infection_Freq            5.97
Hospital_before           5.95
Furanes                   5.95
colistine                 5.94
Diabetes                  5.93
IPM                       5.91
CIP                       5.91
AMC                       5.90
Hypertension              5.88
C                         5.87
AN                        5.86
CZ                        5.86
FOX                       5.84
CTX/CRO                   5.83
Acide nalidixique         5.81
age/gender                5.80
ofx                       5.77
Notes                     1.05
Address                   0.00
ID                        0.00
Name                      0.00
Email                     0.00

In [10]:
# %%
# Duplicados por ID
n_ids = df[ID_COL].nunique(dropna=True)
n_rows = len(df)
n_dup_ids = n_rows - n_ids

print(f"Número de filas: {n_rows}")
print(f"Número de IDs únicos ({ID_COL}): {n_ids}")
print(f"Filas con ID duplicado (potencialmente problemáticas): {n_dup_ids}")

# Duplicados de fila completa
n_dup_rows = df.duplicated().sum()
print(f"Filas completamente duplicadas: {n_dup_rows}")

Número de filas: 10710
Número de IDs únicos (ID): 10710
Filas con ID duplicado (potencialmente problemáticas): 0
Filas completamente duplicadas: 0

In [11]:
# 💊 7. Exploración de codificaciones S/I/R por antibiótico
# Aquí solo miramos los valores distintos y su frecuencia relativa, para ver el desorden que luego normalizaremos.
# %%
def value_counts_normalized(series: pd.Series, max_categories: int = 15) -> pd.DataFrame:
    """Devuelve una tabla con conteos y porcentaje relativo."""
    vc = (
        series.astype("string")
              .str.strip()
              .str.lower()
              .value_counts(dropna=False)
    )

    total = vc.sum()
    df_vc = (
        vc.to_frame(name="count")
          .reset_index()
          .rename(columns={"index": "valor"})
    )
    df_vc["pct"] = (df_vc["count"] / total * 100).round(2)
    return df_vc.head(max_categories)


for col in ANTIBIOTIC_COLS:
    print("=" * 80)
    print(f"Antibiótico: {col}")
    display(value_counts_normalized(df[col]))

================================================================================
Antibiótico: AMX/AMP

        AMX/AMP  count    pct
0             r   5712  53.33
1             s   4061  37.92
2          <NA>    658   6.14
3             i     93   0.87
4  intermediate     91   0.85
5       missing     51   0.48
6             ?     44   0.41

================================================================================
Antibiótico: AMC

            AMC  count    pct
0             r   5815   54.3
1             s   3970  37.07
2          <NA>    632    5.9
3             i     97   0.91
4  intermediate     75    0.7
5       missing     66   0.62
6             ?     55   0.51

================================================================================
Antibiótico: CZ

             CZ  count    pct
0             r   5690  53.13
1             s   4097  38.25
2          <NA>    628   5.86
3  intermediate     98   0.92
4             i     72   0.67
5       missing     66   0.62
6             ?     59   0.55

================================================================================
Antibiótico: FOX

            FOX  count    pct
0             r   5735  53.55
1             s   4049  37.81
2          <NA>    625   5.84
3             i     93   0.87
4  intermediate     80   0.75
5             ?     71   0.66
6       missing     57   0.53

================================================================================
Antibiótico: CTX/CRO

        CTX/CRO  count    pct
0             r   5748  53.67
1             s   4026  37.59
2          <NA>    624   5.83
3             i     95   0.89
4  intermediate     88   0.82
5             ?     68   0.63
6       missing     61   0.57

================================================================================
Antibiótico: IPM

            IPM  count    pct
0             r   5717  53.38
1             s   4054  37.85
2          <NA>    633   5.91
3             i     94   0.88
4  intermediate     92   0.86
5       missing     62   0.58
6             ?     58   0.54

================================================================================
Antibiótico: GEN

            GEN  count    pct
0             s   7854  73.33
1             r   1936  18.08
2          <NA>    643    6.0
3             i     84   0.78
4  intermediate     83   0.77
5       missing     56   0.52
6             ?     54    0.5

================================================================================
Antibiótico: AN

             AN  count    pct
0             s   7875  73.53
1             r   1905  17.79
2          <NA>    628   5.86
3  intermediate     94   0.88
4             i     83   0.77
5       missing     66   0.62
6             ?     59   0.55

================================================================================
Antibiótico: Acide nalidixique

  Acide nalidixique  count    pct
0                 s   8379  78.24
1                 r   1388  12.96
2              <NA>    622   5.81
3      intermediate     99   0.92
4                 i     91   0.85
5                 ?     73   0.68
6           missing     58   0.54

================================================================================
Antibiótico: ofx

            ofx  count    pct
0             s   8406  78.49
1             r   1381  12.89
2          <NA>    618   5.77
3             i     88   0.82
4  intermediate     82   0.77
5             ?     76   0.71
6       missing     59   0.55

================================================================================
Antibiótico: CIP

            CIP  count    pct
0             s   8331  77.79
1             r   1447  13.51
2          <NA>    633   5.91
3  intermediate     96    0.9
4             i     83   0.77
5             ?     61   0.57
6       missing     59   0.55

================================================================================
Antibiótico: C

              C  count    pct
0             s   8390  78.34
1             r   1385  12.93
2          <NA>    629   5.87
3             i     97   0.91
4  intermediate     85   0.79
5       missing     66   0.62
6             ?     58   0.54

================================================================================
Antibiótico: Co-trimoxazole

  Co-trimoxazole  count    pct
0              s   8370  78.15
1              r   1413  13.19
2           <NA>    640   5.98
3   intermediate     97   0.91
4              i     77   0.72
5              ?     67   0.63
6        missing     46   0.43

================================================================================
Antibiótico: Furanes

        Furanes  count    pct
0             s   8457  78.96
1             r   1326  12.38
2          <NA>    637   5.95
3             i     93   0.87
4  intermediate     81   0.76
5             ?     65   0.61
6       missing     51   0.48

================================================================================
Antibiótico: colistine

      colistine  count    pct
0             s   8428  78.69
1             r   1338  12.49
2          <NA>    636   5.94
3  intermediate     96    0.9
4             i     95   0.89
5       missing     65   0.61
6             ?     52   0.49

In [12]:
# ❤️‍🩹 8. Exploración de codificaciones en factores de riesgo
# %%
for col in RISK_FACTOR_COLS:
    print("=" * 80)
    print(f"Factor de riesgo: {col}")
    display(value_counts_normalized(df[col]))

================================================================================
Factor de riesgo: Diabetes

  Diabetes  count    pct
0       no   7883   73.6
1     true   2064  19.27
2     <NA>    635   5.93
3        ?     64    0.6
4  missing     64    0.6

================================================================================
Factor de riesgo: Hypertension

  Hypertension  count    pct
0           no   7470  69.75
1          yes   2477  23.13
2         <NA>    630   5.88
3      missing     73   0.68
4            ?     60   0.56

================================================================================
Factor de riesgo: Hospital_before

  Hospital_before  count    pct
0              no   7008  65.43
1             yes   2939  27.44
2            <NA>    637   5.95
3         missing     64    0.6
4               ?     62   0.58

================================================================================
Factor de riesgo: Infection_Freq

  Infection_Freq  count    pct
0            2.0   2966  27.69
1            1.0   2889  26.97
2            3.0   1963  18.33
3            0.0   1896   17.7
4           <NA>    639   5.97
5        missing    131   1.22
6        unknown     81   0.76
7          error     81   0.76
8              ?     64    0.6

In [13]:
# 👤 9. Exploración rápida de age/gender y Souches
# %%
print("=== age/gender (ejemplos y distribución) ===")
display(value_counts_normalized(df["age/gender"], max_categories=20))

print("\n=== Souches (ejemplos de especies) ===")
species_sample = (
    df["Souches"]
    .dropna()
    .astype(str)
    .str.strip()
    .value_counts()
    .head(20)
    .to_frame(name="count")
)
species_sample

=== age/gender (ejemplos y distribución) ===

   age/gender  count   pct
0        <NA>    621   5.8
1        40/f    167  1.56
2        50/f    159  1.48
3        46/f    154  1.44
4        48/f    149  1.39
5        45/f    148  1.38
6        38/f    137  1.28
7        41/f    136  1.27
8        47/f    135  1.26
9        44/f    131  1.22
10       43/f    128   1.2
11       16/f    121  1.13
12       15/f    120  1.12
13       13/f    120  1.12
14       42/f    116  1.08
15       18/f    115  1.07
16       17/f    113  1.06
17       36/f    112  1.05
18       37/f    112  1.05
19       19/f    111  1.04

=== Souches (ejemplos de especies) ===

                               count
Souches
?                                 63
missing                           60
S687 E. coli                       3
S2424 Prot.eus mirabilis           3
S4989 Acinetobacter baumannii      3
S564 Escherichia coli              3
S4809 Escherichia coli             3
S4518 Escherichia coli             3
S4777 Escherichia coli             3
S3965 Escherichia coli             3
S597 Escherichia coli              3
S2180 Escherichia coli             3
S3413 Escherichia coli             3
S1836 Klebsiella pneumoniae        3
S6401 Escherichia coli             3
S6533 Proteus mirabilis            3
S6855 Escherichia coli             3
S6976 Escherichia coli             3
S7731 Escherichia coli             3
S7821 E. coli                      3